apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app-prod
  namespace: devops
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/simple-argocd-app
    targetRevision: HEAD
    path: k8s/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
