apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app-prod
  namespace: argocd  # Argo CD is installed in this namespace
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nolet7/simple-argocd-app
    targetRevision: HEAD
    path: k8s/production
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
