apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: nolet7/simple-argocd-app:latest
        ports:
        - containerPort: 3000
