name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Image Tag
        run: echo "TAG=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Tag Docker Image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-argocd-app:${TAG} \
                       -t ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-argocd-app:latest \
                       -t ${{ secrets.DOCKER_USERNAME }}/simple-argocd-app:${TAG} \
                       -t ${{ secrets.DOCKER_USERNAME }}/simple-argocd-app:latest .

      - name: Push to GHCR
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-argocd-app:${TAG}
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-argocd-app:latest

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-argocd-app:${TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-argocd-app:latest

      - name: Patch image tag in dev and prod manifests
        run: |
          sed -i "s|noletengine/simple-argocd-app:.*|noletengine/simple-argocd-app:${TAG}|" k8s/dev/deployment.yaml
          sed -i "s|noletengine/simple-argocd-app:.*|noletengine/simple-argocd-app:${TAG}|" k8s/production/deployment.yaml

      - name: Commit and push updated manifests
        run: |
         
      - name: Sync ArgoCD Applications
        run: |
          argocd login 192.168.0.171:32443 --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
          argocd app sync simple-app-dev
          argocd app sync simple-app-prod
