name: CI Build & Push to GHCR and Docker Hub

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Optional: for versioned releases like v1.0.0

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image tag
        id: vars
        run: echo "TAG=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      # --- GHCR Login & Push ---
      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      # --- Docker Hub Login ---
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # --- Build Docker image with multiple tags ---
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-argocd-app:${TAG} \
                       -t ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-argocd-app:latest \
                       -t ${{ secrets.DOCKER_USERNAME }}/simple-argocd-app:${TAG} \
                       -t ${{ secrets.DOCKER_USERNAME }}/simple-argocd-app:latest .

      # --- Push to GHCR ---
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-argocd-app:${TAG}
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-argocd-app:latest

      # --- Push to Docker Hub ---
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-argocd-app:${TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-argocd-app:latest
