name: CI Build & Push to GHCR and Docker Hub

on:
  push:
    branches:
      - feature_dev  # Only run on feature_dev branch
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image tag from short SHA
        run: echo "TAG=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      # GHCR login
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      # Docker Hub login
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build Docker images
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-argocd-app:${TAG} \
                       -t ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-argocd-app:latest \
                       -t ${{ secrets.DOCKER_USERNAME }}/simple-argocd-app:${TAG} \
                       -t ${{ secrets.DOCKER_USERNAME }}/simple-argocd-app:latest .

      # Push images to GHCR
      - name: Push to GHCR
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-argocd-app:${TAG}
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/simple-argocd-app:latest

      # Push images to Docker Hub
      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-argocd-app:${TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/simple-argocd-app:latest

      # Update Kubernetes deployment manifest
      - name: Patch image tag in dev deployment.yaml
        run: |
          sed -i "s|simple-argocd-app:latest|simple-argocd-app:${TAG}|g" k8s/dev/deployment.yaml

      # Commit and push changes
      - name: Commit and push updated manifest
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add k8s/dev/deployment.yaml
          git commit -m "CI: update image tag to ${TAG}" || echo "No changes to commit"
          git push origin feature_dev
